/**
 * @brief Protocol constant definition file.
 * 
 * @author Leonardo G.
 */
#pragma once

enum {
    PROTO_BUFFER_START_SET = 0,
    PROTO_BUFFER_REPLACE,
    PROTO_BUFFER_INSERT,
    PROTO_BUFFER_ROTATE,
    PROTO_BUFFER_SHIFT,
    PROTO_BUFFER_FILL,
    PROTO_BUFFER_SETINDEX,

    PROTO_BUFFER_READ = 0x10,

    PROTO_STRIP_GET_COUNT = 0x20,
    PROTO_STRIP_CHANGE_COUNT,

    PROTO_STRIP_GET_STATE,
    PROTO_STRIP_CHANGE_STATE,

    PROTO_DEVICE_GET_STRIP_COUNT = 0xFE,
    PROTO_VENDOR_SPECIFIC = 0xFF,
};