#pragma once

enum {
    PROTO_BUFFER_START_SET = 0,
    PROTO_BUFFER_SPLICE,
    PROTO_BUFFER_INSERT,
    PROTO_BUFFER_ROTATE,
    PROTO_BUFFER_SHIFT,

    PROTO_BUFFER_READ,

    PROTO_STRIP_GET_COUNT,
    PROTO_STRIP_CHANGE_COUNT,

    PROTO_STRIP_CHANGE_STATE,

    PROTO_VENDOR_SPECIFIC = 255,
};